apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
  namespace: default
#common configuration shared between all applications
data:
  application.yml: |-
    configserver:
      name: Consul
      status: Connected to Consul running in Kubernetes
    jhipster:
      security:
        authentication:
          jwt:
            base64-secret: ZWQ0MjFmNmQzMzQxMGMyZjBmNjllNTE1YTQ3Y2JiODA3ZDcwMTQ2MTljNmE4MjM0ZTY0NzAwZmU1ZGI4NmU2MmY5MmJkZDFkOWE1N2JmNjU1Y2RjZDJiNTEyNDZjZjY4ZGJjMw==
  # app specific configuration
