commonLabels:
  app.kubernetes.io/genereted-by: JHipster

resources:
  # Individual apps
  - monolith-k8s/monolith-deployment.yml
  - monolith-k8s/monolith-service.yml
  - monolith-k8s/monolith-mysql.yml
  # service discovery eureka/consul
  - registry-k8s/consul.yml
  - registry-k8s/consul-config-loader.yml
  - registry-k8s/application-configmap.yml

patchesJson6902:
