apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: harish
      context: ../../harish
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
