apiVersion: v1
kind: Service
metadata:
  name: monolith
  namespace: default
  labels:
    app: monolith
spec:
  selector:
    app: monolith
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
