name: Deploy to EKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Build and Deploy to EKS
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Build Application (Maven)
        run: ./mvnw -Pprod clean package

      - name: Verify Dockerfile
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          if [ -f Dockerfile ]; then
            echo "Dockerfile found!"
          else
            echo "ERROR: Dockerfile not found!"
            exit 1
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}  
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: harish  # Update to match your ECR repo
          IMAGE_TAG: latest
        run: |
          echo "Building Docker image..."
          docker build -t 637423430820.dkr.ecr.us-east-1.amazonaws.com/harish:latest .
          echo "Pushing Docker image..."
          docker push 637423430820.dkr.ecr.us-east-1.amazonaws.com/harish:latest

      - name: Set Up kubectl
        run: |
          aws eks update-kubeconfig --region us-east-1 --name acmf-eks-NXrHnw4W

      - name: Deploy MySQL to EKS
        run: kubectl apply -f harish-k8s/harish-mysql.yml

      - name: Deploy Application to EKS
        run: |
          sed -i "s|image: harish:latest|image: ${{ steps.login-ecr.outputs.registry }}/harish:latest|g" harish-k8s/harish-deployment.yml
          kubectl apply -f harish-k8s/harish-deployment.yml
          kubectl apply -f harish-k8s/harish-service.yml

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/harish --timeout=5m || true
          kubectl get pods -o wide
          kubectl describe deployment harish
          kubectl logs -l app=harish --all-containers=true --prefix
          kubectl get events --field-selector involvedObject.kind=Pod --sort-by=.metadata.creationTimestamp