name: Deploy to EKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Build and Deploy to EKS
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set Up kubectl
        run: |
          aws eks update-kubeconfig --region us-east-1 --name acmf-eks-NXrHnw4W

      - name: Deploy MySQL to EKS
        run: kubectl apply -f harish-k8s/harish-mysql.yml

      - name: Deploy Application to EKS
        run: |
          sed -i "s|image: harish:latest|image: ${{ steps.login-ecr.outputs.registry }}/harish:latest|g" harish-k8s/harish-deployment.yml
          kubectl apply -f harish-k8s/harish-deployment.yml
          kubectl apply -f harish-k8s/harish-service.yml

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/harish --timeout=5m || true
          kubectl get pods -o wide
          kubectl describe deployment harish
          kubectl logs -l app=harish --all-containers=true --prefix
          kubectl get events --field-selector involvedObject.kind=Pod --sort-by=.metadata.creationTimestamp